name: My First Workflow
on:
  push:
    branches:
    - main
  workflow_dispatch: 
  
jobs:
  annotations:
    runs-on: ubuntu-latest
    steps:
    - name: Create warning and error annotation
      run: |
        echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
        echo "::error file=app.js,line=1,col=5,endColumn=7::Error in app.js"