name: Setup Secret and Variable for Repository
on:
  workflow_dispatch

jobs:
  secret-and-var:
    runs-on: ubuntu-latest
    steps:
    - name: Show variable
      run: |
        echo "Variable = ${{ vars.MY_VAR }}"
    - name: Show secret
      run: |
        echo "Secret = ${{ secrets.MY_SECRET }}"
        